name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
      - stage
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/develop'
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug Environment and Secrets
        run: |
          echo "Current environment: ${{ github.event.environment || 'Not set' }}"
          echo "Environment name from job: ${{ env.ENVIRONMENT_NAME || 'Not set' }}"
          echo "GitHub ref: ${{ github.ref }}"
          if [ -n "${{ secrets.AWS_S3 }}" ]; then
            echo "AWS_S3 secret is set"
          else
            echo "AWS_S3 secret is empty"
          fi
          echo "Available secrets:"
          env | grep -i secret

      - name: Deploy to S3 and Invalidate CloudFront
        run: |
          aws s3 sync dist/ s3://${{ secrets.AWS_S3 }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT }} --paths "/*"
