name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
      - stage
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

  #      - name: Run Cypress Tests
  #        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug Environment and Secrets
        run: |
          echo "=== Debug Information ==="
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Current Environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}"
          echo "Job Environment: ${{ env.ENVIRONMENT_NAME }}"
          echo "GitHub Event Environment: ${{ github.event.environment }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Event Action: ${{ github.event.action }}"
          echo "=== Secrets Check ==="
          if [ -n "${{ secrets.AWS_S3 }}" ]; then
            echo "AWS_S3 secret is set"
          else
            echo "AWS_S3 secret is empty"
          fi
          echo "Available secrets:"
          env | grep -i secret

      - name: Debug S3 Bucket
        env:
          S3_BUCKET: ${{ secrets.AWS_S3 }}
        run: |
          echo "Bucket name length: ${#S3_BUCKET}"
          echo "Checking for invalid characters..."
          if [[ $S3_BUCKET == *":"* ]]; then
            echo "Error: Bucket name contains ':' character"
          fi
          if [[ $S3_BUCKET == *"s3://"* ]]; then
            echo "Error: Bucket name contains 's3://' prefix"
          fi
          if [[ $S3_BUCKET =~ ^[a-zA-Z0-9.\-_]{1,255}$ ]]; then
            echo "S3 bucket name is valid"
          else
            echo "S3 bucket name is invalid"
            echo "Bucket names must:"
            echo "- Contain only a-z, A-Z, 0-9, periods, hyphens, and underscores"
            echo "- Be between 1 and 255 characters"
          fi

      - name: Deploy to S3 and Invalidate CloudFront
        env:
          S3_BUCKET: ${{ secrets.AWS_S3 }}
        run: |
          aws s3 sync dist/ s3://${S3_BUCKET} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT }} --paths "/*"
